/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package utilities;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import viewmodel.PhaCheSanPhamViewModel;


/**
 *
 * @author ttuan
 */
public class PhaCheSanPhamJPanel extends javax.swing.JPanel {
    
    private static Icon resizeIcon(ImageIcon icon, int width, int height) {
        Image img = icon.getImage();
        Image resizedImage = img.getScaledInstance(182, 144, Image.SCALE_SMOOTH);
        return new ImageIcon(resizedImage);
    }
    
    /**
     * Creates new form PhaCheSanPhamJPanel
     */
    public PhaCheSanPhamJPanel(PhaCheSanPhamViewModel sp) {
        initComponents();
        try {
            BufferedImage img;

            byte[] pximg = sp.getAnh().getBytes(1, (int) sp.getAnh().length());
            InputStream in = new ByteArrayInputStream(pximg);
            img = ImageIO.read(in);
            ImageIcon anh = new ImageIcon(img);
            lblAnhSP.setIcon(resizeIcon(anh, lblAnhSP.getWidth(), lblAnhSP.getHeight()));
        } catch (Exception e) {
        }
        lblTenSP.setText(sp.getTen().length()>=20 ? sp.getTen().substring(0, 20)+"..." : sp.getTen());
        
        
        if(sp.getTrangThaiSP().equals("Hết hàng")){
            lblTrangThaiSP.setForeground(Color.RED);
            lblTrangThaiSP.setText(sp.getTrangThaiSP());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnhSP = new javax.swing.JLabel();
        lblTenSP = new javax.swing.JLabel();
        lblTrangThaiSP = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 242, 232));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(0, 51, 255), new java.awt.Color(255, 51, 0), new java.awt.Color(255, 0, 51)));

        lblTenSP.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        lblTenSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblTrangThaiSP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTrangThaiSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTrangThaiSP, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(lblTenSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAnhSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnhSP, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTrangThaiSP, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAnhSP;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblTrangThaiSP;
    // End of variables declaration//GEN-END:variables
}
